const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 4.5,
      newReviews: 10,
      description: "high qaulity product",
    },
    {
        _id: "2",
        name: "Adidas Slim shirt",
        category: "Shirts",
        image: "/images/p2.jpg",
        price: 120,
        brand: "Adidas",
        rating: 4.5,
        newReviews: 10,
        description: "high qaulity product",
      },
      {
        _id: "3",
        name: "Lacoste Slim shirt",
        category: "Shirts",
        image: "/images/p3.jpg",
        price: 220,
        brand: "Lacoste",
        rating: 4.5,
        newReviews: 10,
        description: "high qaulity product",
      },
      {
        _id: "4",
        name: "Nike Slim shirt",
        category: "Pants",
        image: "/images/p4.jpg",
        price:78,
        brand: "Nike",
        rating: 4.5,
        newReviews: 14,
        description: "high qaulity product",
      },
      {
        _id: "5",
        name: "Puma Slim shirt",
        category: "Pants",
        image: "/images/p5.jpg",
        price: 120,
        brand: "Puma",
        rating: 4.5,
        newReviews: 10,
        description: "high qaulity product",
      },
      {
        _id: "6",
        name: "Adidas fit pants",
        category: "Shirts",
        image: "/images/p6.jpg",
        price: 120,
        brand: "Adidas",
        rating: 4.5,
        newReviews: 10,
        description: "high qaulity product",
      },

  ],
};


export default data;